const Images = {
    getStarted1: require('./../../assets/Objects.png'),
    getStarted2: require('./../../assets/object2.png'),
    getStarted3: require('./../../assets/object3.png'),
    getStarted4: require('./../../assets/object4.png'),
    // phone: require('./../../assets/icon_Contactnumber.png'),
    next: require('./../../assets/btn_next_signin.png'),
    fbBtn: require('./../../assets/btn_facebook.png'),
    backImage: require('./../../assets/icon_back.png'),
    verify: require('./../../assets/verify.png'),
    GroupPass: require('./../../assets/GroupPass.png'),
    googleBtn: require('./../../assets/btn_google.png'),
    doneBtn: require('./../../assets/btn_Done.png'),
    nameIcon: require('./../../assets/name.png'),
    signUpBtn: require('./../../assets/btn_Signup.png'),
    emailIcon: require('./../../assets/icon_email.png'),
    filter: require('./../../assets/icon_filter.png'),
    menu: require('./../../assets/icon_menu.png'),
    logoHome: require('./../../assets/LogoHome.png'),
    translation: require('./../../assets1/translation.png'),
    icon1: require('./../../assets/Visitors.png'),
    icon2: require('./../../assets/Tenant.png'),
    icon3: require('./../../assets/MyFamily.png'),
    icon5: require('./../../assets/Resident.png'),
    icon4: require('./../../assets/Manage.png'),
    icon6: require('./../../assets/MyStaff.png'),
    icon7: require('./../../assets/Manage-1.png'),

    calendarIcon: require('./../../assets/btn_calendar.png'),
    myDocumentIcon: require('./../../assets/myDocument.png'),
    myreportIcon: require('./../../assets/myreport.png'),

    home: require('./../../assets/icon_home.png'),
    bookAppointment: require('./../../assets/icon_BookAppointment.png'),
    askQuery: require('./../../assets/askQuery.png'),
    ivfG: require('./../../assets/icon_guide_.png'),
    ivfBlogs: require('./../../assets/icon_blogs.png'),
    patient: require('./../../assets/icon_patients.png'),
    logoutIcon: require('./../../assets/logout.png'),
    setting: require('./../../assets/gear.png'),
    
    profilePic: require('./../../assets/pic_profile.png'),
    navjeet: require('./../../assets/navjeet.jpg'),
    sumeeetpal: require('./../../assets/sumeeetpal.jpg'),
    simran: require('./../../assets/simran.jpg'),
    sanjana: require('./../../assets/sanjana.jpg'),

    nextArrow: require('./../../assets/nextArrow.png'),
    bookIcon: require('./../../assets/book.png'),
    placeIcon: require('./../../assets/place.png'),
    upIcon: require('./../../assets/upArrow.png'),
    downIcon: require('./../../assets/downArrow.png'),
    viewIcon: require('./../../assets/view.png'),
    editIcon: require('./../../assets/edit.png'),
    editprofileIcon: require('./../../assets/edit_profile.png'),
    plusIcon: require('./../../assets/more.png'),

    ivf1: require('./../../assets/ivf1.png'),
    ivf2: require('./../../assets/ivf2.png'),
    ivf3: require('./../../assets/ivf3.png'),
    ivf4: require('./../../assets/ivf4.png'),

    user: require('./../../assets/user.png'),
    AddIcon: require('./../../assets/Add-Icon.png'),
    about: require('./../../assets/about.png'),

//
chatDoctor: require('./../../assets/icon_chat.png'),



Logo: require('./../../assets1/Logo.png'),
phone: require('./../../assets1/phone.png'),
password: require('./../../assets1/lock.png'),
banner: require('./../../assets1/banner.jpeg'),
opd: require('./../../assets1/opd.png'),
Vcall: require('./../../assets1/Vcall.png'),

amandeep: require('./../../assets1/amandeep.png'),
radioInActive: require('./../../assets1/radioInActive.png'),
radioActive: require('./../../assets1/radioActive.png'),
calendar: require('./../../assets1/calendar.png'),
covidHome: require('./../../assets1/covidHome.png'),
cancel: require('./../../assets1/cross-1.png'),
tick: require('./../../assets1/cross.png'),
question: require('./../../assets1/question.png'),
training: require('./../../assets1/training.png'),
vital: require('./../../assets1/vital.png'),

Image3: require('./../../assets1/Image3.png'),
user32: require('./../../assets1/user32.png'),
tickNew: require('./../../assets1/tick.png'),
arrow: require('./../../assets1/arrow.png'),
flagRed: require('./../../assets1/flagRed.png'),
flagGreen: require('./../../assets1/flagGreen.png'),
pdfImage: require('./../../assets1/pdfImage.png'),
log: require('./../../assets1/log.png'),
bgNewDark: require('./../../assets1/bgNewDark.png'),
bgNewLight: require('./../../assets1/bgNewLight.png'),
splash: require('./../../assets1/splash.jpg'),
button: require('./../../assets1/button.png'),
ban3: require('./../../assets1/ban3.jpg'),
ban4: require('./../../assets1/ban4.png'),

two: require('./../../assets1/two.png'),
three: require('./../../assets1/three.png'),
one: require('./../../assets1/one.png'),
four: require('./../../assets1/four.png'),
five: require('./../../assets1/five.png'),
userNew: require('./../../assets1/userNew.png'),
reportNew: require('./../../assets1/reportNew.png'),
search: require('./../../assets1/search.png'),

homeM: require('./../../assets1/homeM.png'),
questionM: require('./../../assets1/questionM.png'),
trainingM: require('./../../assets1/trainingM.png'),
vitalM: require('./../../assets1/vitalM.png'),
cross2: require('./../../assets1/cross2.png'),
userMenu: require('./../../assets1/userMenu.png'),
}
export default Images;